# -*- coding: utf-8 -*-
"""fastAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFZ_TA_HxBui6eoVNyLIE-tX9uPweDPz
"""

from fastapi import FastAPI
from pydantic import BaseModel
from model import FakeNewsModel

app = FastAPI(title="Fake News Detection API")

model = FakeNewsModel()


class NewsRequest(BaseModel):
    text: str


@app.post("/predict")
def predict(req: NewsRequest):

    result = model.predict(req.text)

    explanation = (
        "Model detected language patterns typical of "
        + ("reliable" if result["label"] == "POSITIVE" else "unreliable")
        + " content."
    )

    return {
        "prediction": result["label"],
        "confidence_score": result["confidence"],
        "explanation": explanation
    }