# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFZ_TA_HxBui6eoVNyLIE-tX9uPweDPz
"""

from transformers import pipeline

class FakeNewsModel:
    def __init__(self):
        self.classifier = pipeline(
            "text-classification",
            model="distilbert-base-uncased-finetuned-sst-2-english"
        )

    def predict(self, text: str):
        result = self.classifier(text)[0]

        return {
            "label": result["label"],
            "confidence": float(result["score"])
        }