# -*- coding: utf-8 -*-
"""test_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFZ_TA_HxBui6eoVNyLIE-tX9uPweDPz
"""

from fastapi.testclient import TestClient
from app import app

client = TestClient(app)


def test_predict_endpoint():

    response = client.post(
        "/predict",
        json={
            "text": "The government announced a new AI research initiative."
        }
    )

    assert response.status_code == 200

    data = response.json()

    assert "prediction" in data
    assert "confidence_score" in data